### ISSUE TITLE
Side bar is overlapping with tab components

### ISSUE THREAD

**Issue by singhsanket143** [singhsanket143/AlgoCodeFrontend#12]
Currently if we trigger the sidebar, it starts overlapping with the tab components

<img width="1440" alt="Screenshot 2024-03-10 at 3 25 54 PM" src="https://github.com/singhsanket143/AlgoCodeFrontend/assets/29747452/9359f2d9-c655-4cda-9734-48148ce15cac">

We need to make sure that this overlapping doesn't occur and sidebar's content should only be shown

**Comment by surjeetvermaiitm** [comment]
Sidebar overlapping with tab fixed using z-index css property.

PR Link: https://github.com/singhsanket143/AlgoCodeFrontend/pull/17

Screen shot of Updated UI
![image](https://github.com/singhsanket143/AlgoCodeFrontend/assets/39264542/67b213ca-47b0-4d68-90d3-07da5fb4c9c9)

**Comment by singhsanket143** [comment]
Fixed with commit: cce01690e5cb577eca0305cc60f8702133fcc82c
