### ISSUE TITLE
Remove Page level scroll and Add Scroll in ace editor only

### ISSUE THREAD

**Issue by singhsanket143** [singhsanket143/AlgoCodeFrontend#19]
Currently we have a page level scroll, when we scroll from the ace editor side, this is giving glitchy experience.
<img width="1440" alt="Screenshot 2024-03-17 at 3 10 57 PM" src="https://github.com/singhsanket143/AlgoCodeFrontend/assets/29747452/f2d37738-1377-4a2a-b7f8-e623cf5bd197">

**Comment by ghost** [comment]
Issue fixed in #21 .
