### ISSUE TITLE
Rectify CSS for the Description page 

### ISSUE THREAD

**Issue by singhsanket143** [singhsanket143/AlgoCodeFrontend#7]
Currently there is some spacing coming to the right side of ace-editor, which needs to be resolved and ace editor should take the whole space.

**Comment by kenil-kanani** [comment]
`container` utility class is provided by the tailwind css. So it's adding some css containing media-query to `Description` component. 
- I have removed `container` class.

**Comment by surjeetvermaiitm** [comment]
I have fixed the css which was coming to right side of ace-editor and top extra space for divider.
I have also added typescript types and interfaces to support typescript.

PR Link: https://github.com/singhsanket143/AlgoCodeFrontend/pull/10
